name: Deplpoy to EC2

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    name: Deploy to EC2 on master branch push
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Transfer files to VM
      run: |
        rsync -av --filter='- .git/' --exclude '/node_modules' --exclude '/.env' ./ ${{ secrets.USERNAME }}@${{ secrets.HOST_DNS }}:/home/ubuntu/projeto-worflow/
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        
    - name: SSH into VM and run npm install and npm run build
      run: |
        ssh -o StrictHostKeyChecking=no -i ${{ secrets.EC2_SSH_KEY }} \
        ${{ secrets.USERNAME }}@${{ secrets.HOST_DNS }} \
        "cd /home/ubuntu/projeto-worflow && npm install && npm run build"
